### ISSUE TITLE
Ignore Certain Methods for MethodCallWithArgsParentheses

### ISSUE THREAD

**Issue by gxaAlfie** [gxaAlfie/Banana-Cop#13]
Paco's Suggestion:
`MethodCallWithArgsParentheses` rule catches some `Rails/ActiveAdmin/schema/rspec` DSL methods. these methods don't need parentheses. 

Maybe add these [methods](https://github.com/openSUSE/open-build-service/pull/5509/files#diff-60d3df3c6f0836763f82698122e7ab47) to the whitelist.

**Comment by paaaco** [comment]
some more DSL methods that weren't in the link:

### ActiveAdmin DSL
.register
.register_page

### Formtastic DSL
.input 
.semantic_errors
.has_many

### Arbre DSL 
.para 

### Rspec DSL 
.belong_to _(alias of belongs_to, which is in the list)_

### Schema/migrations
bigint
date 
timestamps
**note:** but maybe just exclude the whole schema file/db migrations directory from this cop?
