### ISSUE TITLE
Add Linter Installation

### ISSUE THREAD

**Issue by gxaAlfie** [gxaAlfie/Banana-Cop#7]
Add Linter Installation Instructions in the Wiki Page for editors used by team. Preferably the main users of the editors make these pages since they are more familiar on its usage

List of editors in use:
- Atom
- Vim
- Sublime
- VS Code
- Spacemacs

**Comment by gxaAlfie** [comment]
Added this [guide](https://github.com/gxaAlfie/Rubocop-Settings/wiki/Setup-ALE-Linter-in-VIM-for-Rubocop-Using-Vundle) for using ALE as linter for VIM editor.

**Comment by arman-miranda** [comment]
I added a guide for configuring the linter for the Spacemacs text editor which could be found [here](https://github.com/gxaAlfie/Banana-Cop/wiki/Setting-Up-Linter-Configurations-for-Spacemacs)

**Comment by gxaAlfie** [comment]
Closing this issue since Paco recommended to just use the Rubocop command on the command line for general use.
